import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Map, Sparkles } from 'lucide-react';
import Navbar from '@/components/Navbar';
import AIRoadmap from '@/components/AIRoadmap';
import { useAuth } from '@/contexts/AuthContext';
import { useUserData } from '@/contexts/UserDataContext';

const Roadmap = () => {
  const navigate = useNavigate();
  const { isAuthenticated } = useAuth();
  const { selectedCareer } = useUserData();
  const [level, setLevel] = useState<'beginner' | 'intermediate' | 'advanced'>('beginner');

  useEffect(() => {
    if (!isAuthenticated) navigate('/auth');
    if (!selectedCareer) navigate('/results');
  }, [isAuthenticated, selectedCareer, navigate]);

  if (!selectedCareer) return null;

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Navbar />
      
      <div className="flex-1 container mx-auto px-4 py-10 max-w-5xl">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          {/* Header */}
          <div className="mb-8">
            <div className="flex items-center gap-3 mb-4">
              <Map className="h-8 w-8 text-primary" />
              <h1 className="text-4xl font-bold">
                Career <span className="gradient-text">Roadmap</span>
              </h1>
            </div>
            <p className="text-muted-foreground text-lg mb-6">
              Your personalized learning path to become a {selectedCareer.title}
            </p>

            {/* Level Selector */}
            <div className="flex items-center gap-3 mb-8 flex-wrap">
              <span className="text-sm font-medium">Select your level:</span>
              <div className="flex gap-2">
                {(['beginner', 'intermediate', 'advanced'] as const).map((l) => (
                  <button
                    key={l}
                    onClick={() => setLevel(l)}
                    className={`px-4 py-2 rounded-lg font-medium text-sm transition-all ${
                      level === l
                        ? 'gradient-bg-primary text-primary-foreground'
                        : 'bg-secondary text-muted-foreground hover:text-foreground'
                    }`}
                  >
                    {l.charAt(0).toUpperCase() + l.slice(1)}
                  </button>
                ))}
              </div>
            </div>

            {/* Info Box */}
            <div className="glass-card rounded-lg p-4 mb-8 border-primary/20 flex items-start gap-3">
              <Sparkles className="h-5 w-5 text-primary flex-shrink-0 mt-0.5" />
              <div>
                <p className="text-sm font-semibold mb-1">AI-Generated Roadmap</p>
                <p className="text-sm text-muted-foreground">
                  This roadmap is generated by AI and includes skills, resources, and projects for each step.
                </p>
              </div>
            </div>
          </div>

          {/* Roadmap Component */}
          <AIRoadmap career={selectedCareer.title} level={level} />
        </motion.div>
      </div>
    </div>
  );
};

export default Roadmap;
